---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: alertmanager
data:
  config.yml: |
     route:
       group_wait: 10s
       group_interval: 30s
       repeat_interval: 30m
       receiver: "slack"
       routes:
         - receiver: "slack"
           group_wait: 10s
           match_re:
             severity: critical|warning
           continue: true
       receivers:
        - name: "slack"
          slack_configs:
          - api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/xxxxxxxxxxxxxxxxxxxxxxxxxxx'
            send_resolved: true
            channel: 'monitoring'
            text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"

