---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
   nginx.conf: |
     upstream backend {
      server backend:8080;
     }

     server {
         listen  80; 

         location / {
             root   /usr/src/app/static/frontend;
             index  index.html index.htm;
         }
         
         location /api
         {
             proxy_pass http://backend;
         }
     }
