---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sausage-store-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  revisionHistoryLimit: 15
  template:
    metadata:
      labels:
        app: {{ .Chart.Name  }}
    spec:
      containers:
        - name: {{ .Chart.Name  }}
          image: "{{ .Values.image}}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_host
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
    {{- end }}
