---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sausage-store-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
  selector:
    matchLabels:
      app:  {{ .Chart.Name }}
  revisionHistoryLimit: 15
  template:
    metadata:
      labels:
        app:  {{ .Chart.Name }}
    spec:
      containers:
        - name:  {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault_host
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault_token
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080 
            initialDelaySeconds: 30
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 6
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
    {{- end }}
